spring:
  application:
    name: sa-bi-covid-19
  datasource:
    url: jdbc:postgresql://serverucb.postgres.database.azure.com:5432/database_bi_covid_19?ssl=true&sslmode=prefer
    username: adminBi@serverucb
    password: Arqui2020
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        legacy_limit_handler: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
      show-sql: true
sa-bi-covid-19:
  security:
    salt: qwertyuiop
    secretJwt: 1234567890
